# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop]
  workflow_dispatch:

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: build-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            local::.
          needs: |
            check

      ## If we're pushing, which must be to main, upload the package as an artefact
      - name: Archive production artifacts
        if: github.event_name != 'push'
        uses: actions/upload-artifact@v3
        with:
          name: package-distribution
          path: |
            harsat_*.tar.gz

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual")'
          error-on: '"error"'
          check-dir: '"check"'
